[package]
name = "btrfsutil"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["libc/std"]

[dependencies]
btrfsutil-sys = { path = "../btrfsutil-sys" }
libc = { version = "0.2", default-features = false }
