[package]
name = "btrfsutil-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { version = "0.2", default-features = false }

[build-dependencies]
bindgen = "0.63"
once_cell = "1.16"
pkg-config = "0.3"
